### ISSUE TITLE
Run tests with `yarprun`

### ISSUE THREAD

**Issue by pattacini** [sgiraz/yInfo-test#1]
Hi @sgiraz 

It is convenient to do the test also in the configuration where we employ the [`yarprun`](http://yarp.it/latest/yarprun.html#yarprun_server) as a broker in place of the `localhost`.

To this end, modify the [XML application](../blob/main/app/scripts/yInfo-test-app.xml#L11-L12) as follows:

```diff
<module>
      <name>test_yInfo</name>
-     <environment>YARP_FORWARD_LOG_ENABLE=1</environment>
-     <node>localhost</node>
+     <node>sgiraz</node>
</module>
```

Also, you have to launch the following command in a terminal prior to running the application:
```console
yarprun --server /sgiraz --log
```

cc @traversaro

**Comment by sgiraz** [comment]
@pattacini @traversaro 
As suggested, I did some tests using the `yarprun`. The problem persists although it appears to be a more stable solution. With a delay of 1 microsecond we still loose some traces, but less compared with the `localhost`.

Furthermore I would notify that `yarplogger` does not track more than 10k function calls. I suppose that this is due to an internal buffer of the `yarplogger` .

**Comment by pattacini** [comment]
>As suggested, I did some tests using the yarprun.

Thanks heaps @sgiraz 👍🏻 

>Furthermore I would notify that yarplogger does not track more than 10k function calls. I suppose that this is due to an internal buffer of the yarplogger .

Yep, that's a known limitation.
